apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-lab
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/guitechnologic/devops
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: messaging-lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true