image: node:20

stages:
  - install
  - test
  - quality
  - security
  - k8s-validate

cache:
  key: node-modules
  paths:
    - node_modules/

# -------------------------
# INSTALL
# -------------------------
install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

# -------------------------
# TESTS
# -------------------------
tests:
  stage: test
  script:
    - |
      if npm run | grep -q " test"; then
        npm test
      else
        echo "No tests found — skipping"
      fi

# -------------------------
# LINT (CODE QUALITY)
# -------------------------
eslint:
  stage: quality
  script:
    - npx eslint . || true

# -------------------------
# DEPENDENCY VULNERABILITIES
# -------------------------
npm_audit:
  stage: security
  script:
    - npm audit --audit-level=high || true

# -------------------------
# SECRET SCAN (HARD CODED TOKENS)
# -------------------------
gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . --verbose --no-git || true

# -------------------------
# TRIVY FILESYSTEM SCAN
# -------------------------
trivy_fs:
  stage: security
  image:
    name: aquasec/trivy:0.50.2
    entrypoint: [""]
  script:
    - trivy fs --severity HIGH,CRITICAL --exit-code 0 .

# -------------------------
# KUBERNETES LINT
# -------------------------


# -------------------------
# KUBERNETES DRY RUN
# -------------------------
kubernetes_dry_run:
  stage: k8s-validate
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl version --client
    - |
      find kubernetes -type f \( -name "*.yml" -o -name "*.yaml" \) \
      -exec kubectl apply --dry-run=client -f {} \;