apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apps-servicemonitor
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - eu-health-interop-lab
      - messaging-lab

  selector:
    matchLabels:
      metrics: "true"

  endpoints:
    - port: http
      path: /metrics
      interval: 15s