apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eu-health
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guitechnologic/devops
    targetRevision: main
    path: kubernetes/apps/eu-health-interop-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: eu-health-interop-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true