apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guitechnologic/devops
    targetRevision: main
    path: kubernetes/apps/messaging-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true